[project]
name = "node"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual>=0.86.1",
    "gevent>=24.11.1",
    "tinyrpc>=1.1.7",
]

[dependency-groups]
dev = [
    "textual-dev>=1.6.1",
]
