# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: network.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rnetwork.proto\x12\x07network\"<\n\x14\x43reateNetworkRequest\x12\x11\n\tleader_ip\x18\x01 \x01(\t\x12\x11\n\tchat_name\x18\x02 \x01(\t\"J\n\x15\x43reateNetworkResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x14\n\x12GetNetworksRequest\"=\n\x13GetNetworksResponse\x12&\n\x08networks\x18\x01 \x03(\x0b\x32\x14.network.NetworkInfo\"D\n\x0bNetworkInfo\x12\x11\n\tleader_ip\x18\x01 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x02 \x01(\t\x12\x11\n\tchat_name\x18\x03 \x01(\t\"\x1d\n\x0fLivenessRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"5\n\x10LivenessResponse\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x1aUpdateNetworkLeaderRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x15\n\rnew_leader_ip\x18\x02 \x01(\t\"?\n\x1bUpdateNetworkLeaderResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcc\x02\n\x0eNetworkService\x12N\n\rCreateNetwork\x12\x1d.network.CreateNetworkRequest\x1a\x1e.network.CreateNetworkResponse\x12G\n\nGetNetwork\x12\x1b.network.GetNetworksRequest\x1a\x1c.network.GetNetworksResponse\x12?\n\x08Liveness\x12\x18.network.LivenessRequest\x1a\x19.network.LivenessResponse\x12`\n\x13UpdateNetworkLeader\x12#.network.UpdateNetworkLeaderRequest\x1a$.network.UpdateNetworkLeaderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATENETWORKREQUEST']._serialized_start=26
  _globals['_CREATENETWORKREQUEST']._serialized_end=86
  _globals['_CREATENETWORKRESPONSE']._serialized_start=88
  _globals['_CREATENETWORKRESPONSE']._serialized_end=162
  _globals['_GETNETWORKSREQUEST']._serialized_start=164
  _globals['_GETNETWORKSREQUEST']._serialized_end=184
  _globals['_GETNETWORKSRESPONSE']._serialized_start=186
  _globals['_GETNETWORKSRESPONSE']._serialized_end=247
  _globals['_NETWORKINFO']._serialized_start=249
  _globals['_NETWORKINFO']._serialized_end=317
  _globals['_LIVENESSREQUEST']._serialized_start=319
  _globals['_LIVENESSREQUEST']._serialized_end=348
  _globals['_LIVENESSRESPONSE']._serialized_start=350
  _globals['_LIVENESSRESPONSE']._serialized_end=403
  _globals['_UPDATENETWORKLEADERREQUEST']._serialized_start=405
  _globals['_UPDATENETWORKLEADERREQUEST']._serialized_end=473
  _globals['_UPDATENETWORKLEADERRESPONSE']._serialized_start=475
  _globals['_UPDATENETWORKLEADERRESPONSE']._serialized_end=538
  _globals['_NETWORKSERVICE']._serialized_start=541
  _globals['_NETWORKSERVICE']._serialized_end=873
# @@protoc_insertion_point(module_scope)
