# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import peer_pb2 as peer__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in peer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinNetwork = channel.unary_unary(
                '/peer.PeerService/JoinNetwork',
                request_serializer=peer__pb2.JoinNetworkRequest.SerializeToString,
                response_deserializer=peer__pb2.JoinNetworkResponse.FromString,
                _registered_method=True)
        self.LeaveNetwork = channel.unary_unary(
                '/peer.PeerService/LeaveNetwork',
                request_serializer=peer__pb2.LeaveNetworkRequest.SerializeToString,
                response_deserializer=peer__pb2.LeaveNetworkResponse.FromString,
                _registered_method=True)
        self.Election = channel.unary_unary(
                '/peer.PeerService/Election',
                request_serializer=peer__pb2.ElectionRequest.SerializeToString,
                response_deserializer=peer__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.Coordinator = channel.unary_unary(
                '/peer.PeerService/Coordinator',
                request_serializer=peer__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=peer__pb2.CoordinatorResponse.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/peer.PeerService/SendMessage',
                request_serializer=peer__pb2.MessageRequest.SerializeToString,
                response_deserializer=peer__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.ReceiveMessage = channel.unary_unary(
                '/peer.PeerService/ReceiveMessage',
                request_serializer=peer__pb2.MessageRequest.SerializeToString,
                response_deserializer=peer__pb2.MessageResponse.FromString,
                _registered_method=True)
        self.LivenessPing = channel.unary_unary(
                '/peer.PeerService/LivenessPing',
                request_serializer=peer__pb2.LivenessPingRequest.SerializeToString,
                response_deserializer=peer__pb2.LivenessPingResponse.FromString,
                _registered_method=True)


class PeerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def JoinNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coordinator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LivenessPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNetwork,
                    request_deserializer=peer__pb2.JoinNetworkRequest.FromString,
                    response_serializer=peer__pb2.JoinNetworkResponse.SerializeToString,
            ),
            'LeaveNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveNetwork,
                    request_deserializer=peer__pb2.LeaveNetworkRequest.FromString,
                    response_serializer=peer__pb2.LeaveNetworkResponse.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=peer__pb2.ElectionRequest.FromString,
                    response_serializer=peer__pb2.ElectionResponse.SerializeToString,
            ),
            'Coordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinator,
                    request_deserializer=peer__pb2.CoordinatorRequest.FromString,
                    response_serializer=peer__pb2.CoordinatorResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=peer__pb2.MessageRequest.FromString,
                    response_serializer=peer__pb2.MessageResponse.SerializeToString,
            ),
            'ReceiveMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveMessage,
                    request_deserializer=peer__pb2.MessageRequest.FromString,
                    response_serializer=peer__pb2.MessageResponse.SerializeToString,
            ),
            'LivenessPing': grpc.unary_unary_rpc_method_handler(
                    servicer.LivenessPing,
                    request_deserializer=peer__pb2.LivenessPingRequest.FromString,
                    response_serializer=peer__pb2.LivenessPingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'peer.PeerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('peer.PeerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/JoinNetwork',
            peer__pb2.JoinNetworkRequest.SerializeToString,
            peer__pb2.JoinNetworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/LeaveNetwork',
            peer__pb2.LeaveNetworkRequest.SerializeToString,
            peer__pb2.LeaveNetworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/Election',
            peer__pb2.ElectionRequest.SerializeToString,
            peer__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Coordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/Coordinator',
            peer__pb2.CoordinatorRequest.SerializeToString,
            peer__pb2.CoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/SendMessage',
            peer__pb2.MessageRequest.SerializeToString,
            peer__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/ReceiveMessage',
            peer__pb2.MessageRequest.SerializeToString,
            peer__pb2.MessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LivenessPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/LivenessPing',
            peer__pb2.LivenessPingRequest.SerializeToString,
            peer__pb2.LivenessPingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
