# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chealth.proto\x12\x03nds\"\x1d\n\rHealthRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eHealthResponse\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x06Health\x12/\n\x04Ping\x12\x12.nds.HealthRequest\x1a\x13.nds.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=21
  _globals['_HEALTHREQUEST']._serialized_end=50
  _globals['_HEALTHRESPONSE']._serialized_start=52
  _globals['_HEALTHRESPONSE']._serialized_end=85
  _globals['_HEALTH']._serialized_start=87
  _globals['_HEALTH']._serialized_end=144
# @@protoc_insertion_point(module_scope)
