# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import network_pb2 as network__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in network_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NetworkServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNetwork = channel.unary_unary(
                '/network.NetworkService/CreateNetwork',
                request_serializer=network__pb2.CreateNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.CreateNetworkResponse.FromString,
                _registered_method=True)
        self.GetNetworks = channel.unary_unary(
                '/network.NetworkService/GetNetworks',
                request_serializer=network__pb2.GetNetworksRequest.SerializeToString,
                response_deserializer=network__pb2.GetNetworksResponse.FromString,
                _registered_method=True)
        self.Liveness = channel.unary_unary(
                '/network.NetworkService/Liveness',
                request_serializer=network__pb2.LivenessRequest.SerializeToString,
                response_deserializer=network__pb2.LivenessResponse.FromString,
                _registered_method=True)
        self.UpdateNetworkLeader = channel.unary_unary(
                '/network.NetworkService/UpdateNetworkLeader',
                request_serializer=network__pb2.UpdateNetworkLeaderRequest.SerializeToString,
                response_deserializer=network__pb2.UpdateNetworkLeaderResponse.FromString,
                _registered_method=True)


class NetworkServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNetwork(self, request, context):
        """Define the createNetwork RPC method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworks(self, request, context):
        """Method to get information about networks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Liveness(self, request, context):
        """Method to check liveness of a node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNetworkLeader(self, request, context):
        """Method to update a network leader
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNetwork,
                    request_deserializer=network__pb2.CreateNetworkRequest.FromString,
                    response_serializer=network__pb2.CreateNetworkResponse.SerializeToString,
            ),
            'GetNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworks,
                    request_deserializer=network__pb2.GetNetworksRequest.FromString,
                    response_serializer=network__pb2.GetNetworksResponse.SerializeToString,
            ),
            'Liveness': grpc.unary_unary_rpc_method_handler(
                    servicer.Liveness,
                    request_deserializer=network__pb2.LivenessRequest.FromString,
                    response_serializer=network__pb2.LivenessResponse.SerializeToString,
            ),
            'UpdateNetworkLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNetworkLeader,
                    request_deserializer=network__pb2.UpdateNetworkLeaderRequest.FromString,
                    response_serializer=network__pb2.UpdateNetworkLeaderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'network.NetworkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('network.NetworkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NetworkService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network.NetworkService/CreateNetwork',
            network__pb2.CreateNetworkRequest.SerializeToString,
            network__pb2.CreateNetworkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network.NetworkService/GetNetworks',
            network__pb2.GetNetworksRequest.SerializeToString,
            network__pb2.GetNetworksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Liveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network.NetworkService/Liveness',
            network__pb2.LivenessRequest.SerializeToString,
            network__pb2.LivenessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNetworkLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network.NetworkService/UpdateNetworkLeader',
            network__pb2.UpdateNetworkLeaderRequest.SerializeToString,
            network__pb2.UpdateNetworkLeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
